### ISSUE TITLE
Until ##:## doesn't get updated 

### ISSUE THREAD

**Issue by AXDOOMER** [otakulan/lanparty-seating#61]
After scanning 3 people to 30, 29 and 28, the until still shows the time from the previous players. 

![IMG_20230812_191316992_HDR](https://github.com/starcraft66/lanparty-seating/assets/6194072/c04949f6-2eb4-4377-8a05-9c9a19aaa67d)

**Comment by AXDOOMER** [comment]
Autre exemple

Seats 77 & 76 

![IMG_20230813_011842841](https://github.com/starcraft66/lanparty-seating/assets/6194072/0eb6fb5c-a1aa-4819-8920-68d1c452ff86)

**Comment by starcraft66** [comment]
This may have been fixed in https://github.com/otakulan/lanparty-seating/pull/64 but needs more in-depth testing to confirm

**Comment by starcraft66** [comment]
We did not observe anything abnormal in 2024, going to close this.
